# Generated by Django 5.2.9 on 2025-12-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_add_models_bus_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
